title = "AmoebaNet-D"

# Model
[model]
num_layers=6
num_filters=190
normbatch=true

# Setting Optimizer
[optimizer]
lr=0.1
mometum=0.9
decay=0.0001

# Device Related Configurations
[gpu]
device=0

# Train Related Configurations
[train]
epoch=200
seed=100000

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="flower102"
    path="./dataset/flower102/train"
    num_classes=102
    train_batch=32
    image_size=416
    num_workers=6
    shuffle=true
    pin_memory=true

  [dataset.test]
    type="flower102"
    path="./dataset/flower102/valid"
    num_classes=102
    test_batch=2
    image_size=416
    num_workers=6
    shuffle=true
    pin_memory=true

# Micro Batch Streaming
[mbs]
enable=false
micro_batch_size=32

# Monitoring tool
[wandb]
wandb=true
