title = "CycleGAN"

# Device Related Configurations
[gpu]
device = 0

# Train Related Configurations
[train]
epoch = 100

# Dataset Related Configurations
[dataset]
  [dataset.train]
    path="./dataset/horse2zebra/train"
    batch_size = 4
    image_size = 256

  [dataset.test]
    path="./dataset/horse2zebra/test"
    batch_size = 4
    image_size = 256

# Micro Batch Streaming
[microbatchstream]
enable = true
micro_batch_size = 4
