title = "VGG"

# Select model version (16, 19)
[model]
normbatch = false
version = 16

# Setting Optimizer
[optimizer]
lr = 0.05
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
device = 0

# Train Related Configurations
[train]
epoch = 100

# Dataset Related Configurations
[dataset]
  [dataset.train]
    path="./dataset/imagenet2012"
    batch_size = 4
    image_size = 256

  [dataset.test]
    path="./dataset/imagenet2012"
    batch_size = 4
    image_size = 256

# Micro Batch Streaming
[microbatchstream]
enable = true
micro_batch_size = 4
