title = "EfficientNet"

# Setting Optimizer
[optimizer]
lr = 0.1
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
device = 1

# Train Related Configurations
[train]
epoch = 10

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="cifar100"
    path="./dataset/"
    num_classes = 100
    batch_size = 256
    image_size = 32
    num_worker = 0
    shuffle = false
    pin_memory = false

  [dataset.test]
    type="cifar100"
    path="./dataset/"
    num_classes = 100
    batch_size = 64
    image_size = 32
    num_worker = 0
    shuffle = false
    pin_memory = false

# Micro Batch Streaming
[microbatchstream]
enable = true
batchnorm = false
micro_batch_size = 64
