title = "EfficientNet"

# Setting Optimizer
[optimizer]
lr = 0.1
mometum = 0.9
decay = 0.0001

# Device Related Configurations
[gpu]
device = 1

# Train Related Configurations
[train]
epoch = 200

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="cifar100"
    path="./dataset/"
    num_classes = 100
    batch_size = 128
    image_size = 32
    num_worker = 16

  [dataset.test]
    type="cifar100"
    path="./dataset/"
    num_classes = 100
    batch_size = 64
    image_size = 256
    num_worker = 16

# Micro Batch Streaming
[microbatchstream]
enable = false
batchnorm = false
micro_batch_size = 64
