title = "EfficientNet"

# Setting Optimizer
[optimizer]
lr = 0.1
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
device = 1

# Train Related Configurations
[train]
epoch = 100

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="cifar10"
    path="./dataset/"
    num_classes = 10
    batch_size = 256
    image_size = 32
    num_worker = 16

  [dataset.test]
    type="cifar10"
    path="./dataset/"
    num_classes = 10
    batch_size = 64
    image_size = 256

# Micro Batch Streaming
[microbatchstream]
enable = false
batchnorm = false
micro_batch_size = 64
