title = "ResNet"

# Model
[model]
version = 50

# Setting Optimizer
[optimizer]
lr = 0.01
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
device = 0

# Train Related Configurations
[train]
epoch = 100
seed = 10000

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="cifar10"
    path="./dataset/cifar10"
    num_classes = 10
    batch_size = 128
    image_size = 32
    num_workers = 0
    shuffle = false
    pin_memory = false

  [dataset.test]
    type="cifar10"
    path="./dataset/cifar10"
    num_classes = 10
    batch_size = 64
    image_size = 32
    num_workers = 0
    shuffle = false
    pin_memory = false

# Micro Batch Streaming
[mbs]
enable = false
batchnorm = false
micro_batch_size = 32

# Monitoring tool
[wandb]
enable = false
