title = "EfficientNet"

# Setting Optimizer
[optimizer]
lr = 0.1
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
<<<<<<< HEAD
device = 1

# Train Related Configurations
[train]
epoch = 10
=======
device = 0

# Train Related Configurations
[train]
epoch = 100
>>>>>>> f2306ef8eb7bc9a9a0af65693227c56d651e6043

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="cifar100"
    path="./dataset/"
    num_classes = 100
<<<<<<< HEAD
    batch_size = 256
    image_size = 32
    num_worker = 0
    shuffle = false
    pin_memory = false
=======
    batch_size = 512
    image_size = 32
    num_worker = 16
>>>>>>> f2306ef8eb7bc9a9a0af65693227c56d651e6043

  [dataset.test]
    type="cifar100"
    path="./dataset/"
    num_classes = 100
    batch_size = 64
<<<<<<< HEAD
    image_size = 32
    num_worker = 0
    shuffle = false
    pin_memory = false
=======
    image_size = 256
>>>>>>> f2306ef8eb7bc9a9a0af65693227c56d651e6043

# Micro Batch Streaming
[microbatchstream]
enable = true
batchnorm = false
micro_batch_size = 64
