title = "EfficientNet"

# Setting Optimizer
[optimizer]
lr = 0.1
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
device = 0

# Train Related Configurations
[train]
epoch = 50

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="imagenet2012"
    path="./dataset/"
    num_classes = 10
    batch_size = 2048
    image_size = 227
    num_worker = 0
    shuffle = false
    pin_memory = false
    prefetch = 2

  [dataset.test]
    type="imagenet2012"
    path="./dataset/"
    num_classes = 10
    batch_size = 64
    image_size = 256
    num_worker = 16

# Micro Batch Streaming
[microbatchstream]
enable = true
batchnorm = true
micro_batch_size = 2
