title = "VGG"

# Select model version (16, 19)
[model]
normbatch = true
version = 16

# Setting Optimizer
[optimizer]
lr = 0.05
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
device = 1

# Train Related Configurations
[train]
epoch = 1

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="cifar10"
    path="./dataset/"
    num_classes = 10
    batch_size = 512
    image_size = 32
    num_worker = 0
    shuffle = false
    pin_memory = false

  [dataset.test]
    type="cifar10"
    path="./dataset/"
    num_classes = 10
    batch_size = 32
    image_size = 32
    num_worker = 0
    shuffle = false
    pin_memory = false

# Micro Batch Streaming
[microbatchstream]
enable = true
batchnorm = false
micro_batch_size = 64
