title = "VGG"

# Select model version (16, 19)
[model]
normbatch = false
version = 16

# Setting Optimizer
[optimizer]
lr = 0.05
mometum = 0.9
decay = 0.0005

# Device Related Configurations
[gpu]
device = 0

# Train Related Configurations
[train]
epoch = 300

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="cifar10"
    path="./dataset/"
    num_classes = 10
    batch_size = 512
    image_size = 32
    num_worker = 16

  [dataset.test]
    type="cifar10"
    path="./dataset/"
    num_classes = 10
    batch_size = 4
    image_size = 256

# Micro Batch Streaming
[microbatchstream]
enable = false
micro_batch_size = 512
