title = "VGG16"

# Model
[model]
version=16
normbatch=true

# Setting Optimizer
[optimizer]
lr=0.01
mometum=0.9
decay=0.0005

# Device Related Configurations
[gpu]
device=0

# Train Related Configurations
[train]
epoch=100
seed=1

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="flower102"
    path="./dataset/flower102/train"
    num_classes=102
    train_batch=1
    image_size=224
    num_workers=6
    shuffle=true
    pin_memory=true

  [dataset.test]
    type="flower102"
    path="./dataset/flower102/valid"
    num_classes=102
    test_batch=1
    image_size=224
    num_workers=6
    shuffle=true
    pin_memory=true

# Micro Batch Streaming
[mbs]
enable=false
micro_batch_size=1

# Monitoring tool
[wandb]
wandb=true
