title = "U-Net"

# Setting Optimizer
[optimizer]
lr=1e-3
mometum=0.9
decay=0.0005

# Device Related Configurations
[gpu]
device=0

# Train Related Configurations
[train]
epoch=200
seed=10000

# Dataset Related Configurations
[dataset]
  [dataset.train]
    type="carvana"
    path="dataset/carvana"
    train_batch=32
    image_size=224
    num_workers=6
    shuffle=true
    pin_memory=true

  [dataset.test]
    type="carvana"
    path="dataset/carvana"
    test_batch=16
    image_size=224
    num_workers=6
    shuffle=true
    pin_memory=true

# Micro Batch Streaming
[mbs]
enable=false
micro_batch_size=16

# Monitoring tool
[wandb]
enable=false